const obj = [
  {
    language: "english",
    question:
      "The capital _placeholder  Paris is known for its beautiful landmarks.",
    options: ["of", "is", "an", "are"],
    correctAnswer: "of",
    userAnswer: null,
    answerPoint: 3,
  },
  {
    language: "english",
    question:
      "The largest _placeholder  in the world is the Great Barrier Reef.",
    options: ["mountain", "desert", "coral reef", "waterfall"],
    correctAnswer: "coral reef",
    userAnswer: null,
    answerPoint: 4,
  },
  {
    language: "english",
    question: "The longest river in the world is the _placeholder .",
    options: ["Nile", "Amazon", "Yangtze", "Mississippi"],
    correctAnswer: "Nile",
    userAnswer: null,
    answerPoint: 2,
  },
  {
    language: "english",
    question: "The smallest country in the world is _placeholder .",
    options: ["Russia", "Vatican City", "Monaco", "Nauru"],
    correctAnswer: "Vatican City",
    userAnswer: null,
    answerPoint: 5,
  },
  {
    language: "english",
    question: "The deepest ocean in the world is the _placeholder .",
    options: [
      "Atlantic Ocean",
      "Indian Ocean",
      "Arctic Ocean",
      "Pacific Ocean",
    ],
    correctAnswer: "Pacific Ocean",
    userAnswer: null,
    answerPoint: 1,
  },
  {
    language: "english",
    question: "The largest desert in the world is the _placeholder .",
    options: ["Sahara Desert", "Arabian Desert", "Gobi Desert", "Antarctica"],
    correctAnswer: "Antarctica",
    userAnswer: null,
    answerPoint: 4,
  },
  {
    language: "english",
    question: "The highest mountain in the world is _placeholder .",
    options: ["Mount Everest", "K2", "Kangchenjunga", "Lhotse"],
    correctAnswer: "Mount Everest",
    userAnswer: null,
    answerPoint: 3,
  },
  {
    language: "english",
    question: "The largest continent in the world is _placeholder .",
    options: ["Asia", "Africa", "North America", "South America"],
    correctAnswer: "Asia",
    userAnswer: null,
    answerPoint: 2,
  },
  {
    language: "english",
    question: "The largest river in the world is the _placeholder .",
    options: ["Nile", "Amazon", "Yangtze", "Mississippi"],
    correctAnswer: "Amazon",
    userAnswer: null,
    answerPoint: 1,
  },
  {
    language: "english",
    question: "The largest island in the world is _placeholder .",
    options: ["Greenland", "Madagascar", "Borneo", "New Guinea"],
    correctAnswer: "Greenland",
    userAnswer: null,
    answerPoint: 5,
  },
  {
    language: "english",
    question: "The largest lake in the world is _placeholder .",
    options: ["Caspian Sea", "Lake Superior", "Lake Victoria", "Lake Huron"],
    correctAnswer: "Caspian Sea",
    userAnswer: null,
    answerPoint: 4,
  },
  {
    language: "english",
    question: "The largest waterfall in the world is _placeholder .",
    options: ["Niagara Falls", "Angel Falls", "Victoria Falls", "Iguazu Falls"],
    correctAnswer: "Angel Falls",
    userAnswer: null,
    answerPoint: 3,
  },
  {
    language: "english",
    question: "The largest country in the world is _placeholder .",
    options: ["Russia", "Canada", "China", "United States"],
    correctAnswer: "Russia",
    userAnswer: null,
    answerPoint: 2,
  },
  {
    language: "english",
    question: "The hottest continent in the world is _placeholder .",
    options: ["Africa", "Australia", "South America", "Asia"],
    correctAnswer: "Africa",
    userAnswer: null,
    answerPoint: 5,
  },
];
