import AuthProvider from "@/providers/AuthProvider";
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <AuthProvider>
          <Toaster position="bottom-right" reverseOrder={false} />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
